[2025-05-02T21:02:38.152+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T21:02:38.168+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T20:36:57.362047+00:00 [queued]>
[2025-05-02T21:02:38.175+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T20:36:57.362047+00:00 [queued]>
[2025-05-02T21:02:38.175+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 1
[2025-05-02T21:02:38.185+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-05-02 20:36:57.362047+00:00
[2025-05-02T21:02:38.203+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T21:02:38.204+0000] {standard_task_runner.py:72} INFO - Started process 312 to run task
[2025-05-02T21:02:38.203+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_sentiment_data_to_snowflake', 'manual__2025-05-02T20:36:57.362047+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp6ua8hsan']
[2025-05-02T21:02:38.208+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask load_sentiment_data_to_snowflake
[2025-05-02T21:02:38.247+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T20:36:57.362047+00:00 [running]> on host 4bc692150671
[2025-05-02T21:02:38.313+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T20:36:57.362047+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T20:36:57.362047+00:00'
[2025-05-02T21:02:38.315+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T21:02:38.326+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T21:02:38.327+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T21:02:38.328+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T21:02:38.328+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T21:02:39.603+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T21:02:39.728+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
