[2025-04-30T20:44:04.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T20:44:04.471+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_YFinance_Snowflake.extract manual__2025-04-30T20:44:01.345998+00:00 [queued]>
[2025-04-30T20:44:04.479+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_YFinance_Snowflake.extract manual__2025-04-30T20:44:01.345998+00:00 [queued]>
[2025-04-30T20:44:04.480+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-30T20:44:04.505+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-04-30 20:44:01.345998+00:00
[2025-04-30T20:44:04.525+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-30T20:44:04.529+0000] {standard_task_runner.py:72} INFO - Started process 298 to run task
[2025-04-30T20:44:04.537+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Stock_YFinance_Snowflake', 'extract', 'manual__2025-04-30T20:44:01.345998+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/Lab_Stocks.py', '--cfg-path', '/tmp/tmp2duburoh']
[2025-04-30T20:44:04.543+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask extract
[2025-04-30T20:44:04.627+0000] {task_command.py:467} INFO - Running <TaskInstance: Stock_YFinance_Snowflake.extract manual__2025-04-30T20:44:01.345998+00:00 [running]> on host 04c21e6bd2dc
[2025-04-30T20:44:04.786+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_YFinance_Snowflake' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T20:44:01.345998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T20:44:01.345998+00:00'
[2025-04-30T20:44:04.790+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-30T20:44:04.819+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
                               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3607, in _connect
    self._add_conn_hooks(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3617, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3632, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Lab_Stocks.py", line 30, in extract
    df = ticker.history(period="180d")  # Fetch 180 days of historical data
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 91, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 97, in _lazy_load_price_history
    self._price_history = PriceHistory(self._data, self.ticker, self._get_ticker_tz(timeout=10))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 104, in _get_ticker_tz
    tz = c.lookup(self.ticker)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/cache.py", line 163, in lookup
    self.initialise()
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/cache.py", line 146, in initialise
    db.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3262, in connect
    with __exception_wrapper__:
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
                               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3607, in _connect
    self._add_conn_hooks(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3617, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3632, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
peewee.OperationalError: database is locked
[2025-04-30T20:44:04.852+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Stock_YFinance_Snowflake, task_id=extract, run_id=manual__2025-04-30T20:44:01.345998+00:00, execution_date=20250430T204401, start_date=20250430T204404, end_date=20250430T204404
[2025-04-30T20:44:04.920+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-30T20:44:04.922+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task extract (database is locked; 298)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
                               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3607, in _connect
    self._add_conn_hooks(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3617, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3632, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Lab_Stocks.py", line 30, in extract
    df = ticker.history(period="180d")  # Fetch 180 days of historical data
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 91, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 97, in _lazy_load_price_history
    self._price_history = PriceHistory(self._data, self.ticker, self._get_ticker_tz(timeout=10))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/base.py", line 104, in _get_ticker_tz
    tz = c.lookup(self.ticker)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/cache.py", line 163, in lookup
    self.initialise()
  File "/home/airflow/.local/lib/python3.12/site-packages/yfinance/cache.py", line 146, in initialise
    db.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3262, in connect
    with __exception_wrapper__:
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
                               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3607, in _connect
    self._add_conn_hooks(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3617, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/peewee.py", line 3632, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
peewee.OperationalError: database is locked
[2025-04-30T20:44:04.968+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-30T20:44:04.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
