[2025-05-02T22:10:45.195+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T22:10:45.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T22:10:40.543057+00:00 [queued]>
[2025-05-02T22:10:45.244+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T22:10:40.543057+00:00 [queued]>
[2025-05-02T22:10:45.244+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T22:10:45.264+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-05-02 22:10:40.543057+00:00
[2025-05-02T22:10:45.280+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=928) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T22:10:45.283+0000] {standard_task_runner.py:72} INFO - Started process 946 to run task
[2025-05-02T22:10:45.295+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_sentiment_data_to_snowflake', 'manual__2025-05-02T22:10:40.543057+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmpmcb9cf_n']
[2025-05-02T22:10:45.303+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask load_sentiment_data_to_snowflake
[2025-05-02T22:10:45.467+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake manual__2025-05-02T22:10:40.543057+00:00 [running]> on host edac5e2fb0a3
[2025-05-02T22:10:45.650+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T22:10:40.543057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T22:10:40.543057+00:00'
[2025-05-02T22:10:45.654+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T22:10:45.674+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T22:10:45.676+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T22:10:45.678+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T22:10:45.679+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T22:10:46.774+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:10:46.898+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:37:16.678+0000] {job.py:229} INFO - Heartbeat recovered after 303.12 seconds
[2025-05-02T22:37:50.930+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='sfedu02-ksb65579.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)")': /queries/01bc1672-0305-1f21-0004-59ff0037daaa/result?request_guid=a5a5a5b2-d606-45c9-9f05-335884d24a2e
[2025-05-02T22:43:15.176+0000] {job.py:229} INFO - Heartbeat recovered after 302.80 seconds
[2025-05-02T22:47:49.981+0000] {job.py:229} INFO - Heartbeat recovered after 103.24 seconds
[2025-05-02T22:52:13.057+0000] {job.py:229} INFO - Heartbeat recovered after 207.56 seconds
[2025-05-02T22:57:38.213+0000] {job.py:229} INFO - Heartbeat recovered after 299.98 seconds
[2025-05-02T23:05:52.570+0000] {job.py:229} INFO - Heartbeat recovered after 438.85 seconds
[2025-05-02T23:20:31.073+0000] {job.py:229} INFO - Heartbeat recovered after 853.24 seconds
[2025-05-02T23:31:19.259+0000] {job.py:229} INFO - Heartbeat recovered after 592.62 seconds
[2025-05-02T23:38:00.076+0000] {job.py:229} INFO - Heartbeat recovered after 345.21 seconds
[2025-05-02T23:55:15.259+0000] {job.py:229} INFO - Heartbeat recovered after 1009.91 seconds
[2025-05-03T00:07:19.369+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-03T00:07:19.376+0000] {logging_mixin.py:190} INFO - âœ… Sentiment data loaded into dev.raw.tesla_tweet_data.
[2025-05-03T00:07:19.381+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-03T00:07:19.451+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-03T00:07:19.452+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tesla_stock_sentiment_api_etl, task_id=load_sentiment_data_to_snowflake, run_id=manual__2025-05-02T22:10:40.543057+00:00, execution_date=20250502T221040, start_date=20250502T221045, end_date=20250503T000719
[2025-05-03T00:07:19.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-03T00:07:19.554+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T00:07:19.555+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
