[2025-05-02T02:57:11.456+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T02:57:11.473+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T02:57:11.480+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T02:57:11.481+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T02:57:11.494+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_stock_data_to_snowflake> on 2025-05-01 02:30:00+00:00
[2025-05-02T02:57:11.517+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9837) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T02:57:11.523+0000] {standard_task_runner.py:72} INFO - Started process 9867 to run task
[2025-05-02T02:57:11.516+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_stock_data_to_snowflake', 'scheduled__2025-05-01T02:30:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp2owb9141']
[2025-05-02T02:57:11.528+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask load_stock_data_to_snowflake
[2025-05-02T02:57:11.625+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [running]> on host d110dddef273
[2025-05-02T02:57:11.726+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_stock_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T02:30:00+00:00'
[2025-05-02T02:57:11.727+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T02:57:11.740+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T02:57:11.741+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T02:57:11.744+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T02:57:11.745+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T02:57:14.709+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T02:57:14.939+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T03:05:47.750+0000] {job.py:229} INFO - Heartbeat recovered after 490.90 seconds
[2025-05-02T04:06:50.224+0000] {job.py:229} INFO - Heartbeat recovered after 3637.14 seconds
[2025-05-02T05:08:09.332+0000] {job.py:229} INFO - Heartbeat recovered after 3623.15 seconds
[2025-05-02T05:08:19.568+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-02T05:08:19.581+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-02T05:08:19.583+0000] {process_utils.py:132} INFO - Sending 15 to group 9867. PIDs of all processes in the group: [9867]
[2025-05-02T05:08:19.584+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 9867
[2025-05-02T05:08:19.586+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-02T05:08:19.639+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-02T05:08:19.685+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=9867, status='terminated', exitcode=0, started='02:57:11') (9867) terminated with exit code 0
[2025-05-02T22:02:49.574+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T22:02:49.598+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T22:02:49.607+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T22:02:49.607+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T22:02:49.623+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_stock_data_to_snowflake> on 2025-05-01 02:30:00+00:00
[2025-05-02T22:02:49.642+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=573) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T22:02:49.644+0000] {standard_task_runner.py:72} INFO - Started process 589 to run task
[2025-05-02T22:02:49.644+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_stock_data_to_snowflake', 'scheduled__2025-05-01T02:30:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp67w3w5lt']
[2025-05-02T22:02:49.651+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask load_stock_data_to_snowflake
[2025-05-02T22:02:49.754+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_stock_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [running]> on host edac5e2fb0a3
[2025-05-02T22:02:49.869+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_stock_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T02:30:00+00:00'
[2025-05-02T22:02:49.871+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T22:02:49.897+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T22:02:49.900+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T22:02:49.902+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T22:02:49.904+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T22:02:52.058+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:02:52.169+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:06:02.287+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:06:02.294+0000] {logging_mixin.py:190} INFO - âœ… Stock data (via Alpha Vantage) loaded into dev.raw.tesla_stock_data.
[2025-05-02T22:06:02.302+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-02T22:06:02.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-02T22:06:02.329+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tesla_stock_sentiment_api_etl, task_id=load_stock_data_to_snowflake, run_id=scheduled__2025-05-01T02:30:00+00:00, execution_date=20250501T023000, start_date=20250502T220249, end_date=20250502T220602
[2025-05-02T22:06:02.370+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-02T22:06:02.400+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T22:06:02.402+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
