[2025-05-01T02:30:01.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T02:30:01.833+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment__etl.load_sentiment_data_to_snowflake scheduled__2025-04-30T02:30:00+00:00 [queued]>
[2025-05-01T02:30:01.841+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment__etl.load_sentiment_data_to_snowflake scheduled__2025-04-30T02:30:00+00:00 [queued]>
[2025-05-01T02:30:01.842+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-01T02:30:01.852+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-04-30 02:30:00+00:00
[2025-05-01T02:30:01.867+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5767) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T02:30:01.869+0000] {standard_task_runner.py:72} INFO - Started process 5773 to run task
[2025-05-01T02:30:01.868+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment__etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-04-30T02:30:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp8nmfzrha']
[2025-05-01T02:30:01.871+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask load_sentiment_data_to_snowflake
[2025-05-01T02:30:01.937+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment__etl.load_sentiment_data_to_snowflake scheduled__2025-04-30T02:30:00+00:00 [running]> on host 04c21e6bd2dc
[2025-05-01T02:30:02.068+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment__etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-30T02:30:00+00:00'
[2025-05-01T02:30:02.070+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-01T02:30:02.093+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-01T02:30:02.096+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-01T02:30:02.097+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T02:30:02.098+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T02:30:03.100+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T02:30:03.318+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T02:39:53.990+0000] {job.py:229} INFO - Heartbeat recovered after 364.78 seconds
[2025-05-01T02:39:59.083+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-01T02:39:59.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-01T02:39:59.087+0000] {process_utils.py:132} INFO - Sending 15 to group 5773. PIDs of all processes in the group: [5773]
[2025-05-01T02:39:59.088+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 5773
[2025-05-01T02:39:59.090+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-01T02:39:59.146+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-01T02:39:59.187+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5773, status='terminated', exitcode=0, started='02:30:01') (5773) terminated with exit code 0
